run_config:
  name: Loan-default-prediction
  author: 
  version: default
  description: Loan default prediction project using AWS
  dependencies: requirements.txt
  data_source: data/subsample_train.csv
  warnings_setting: ignore

create_dataset:
  drop_columns:
    - "SK_ID_CURR"
    - "OWN_CAR_AGE"
    - "FLAG_EMP_PHONE"
    - "FLAG_WORK_PHONE"
    - "FLAG_CONT_MOBILE"
    - "FLAG_PHONE"
    - "EXT_SOURCE_1"
    - "EXT_SOURCE_2"
    - "EXT_SOURCE_3"
    - "BASEMENTAREA_AVG"
    - "YEARS_BEGINEXPLUATATION_AVG"
    - "YEARS_BUILD_AVG"
    - "COMMONAREA_AVG"
    - "ELEVATORS_AVG"
    - "ENTRANCES_AVG"
    - "FLOORSMAX_AVG"
    - "FLOORSMIN_AVG"
    - "LANDAREA_AVG"
    - "LIVINGAPARTMENTS_AVG"
    - "LIVINGAREA_AVG"
    - "NONLIVINGAPARTMENTS_AVG"
    - "NONLIVINGAREA_AVG"
    - "APARTMENTS_MODE"
    - "BASEMENTAREA_MODE"
    - "YEARS_BEGINEXPLUATATION_MODE"
    - "YEARS_BUILD_MODE"
    - "COMMONAREA_MODE"
    - "ELEVATORS_MODE"
    - "ENTRANCES_MODE"
    - "FLOORSMAX_MODE"
    - "FLOORSMIN_MODE"
    - "LANDAREA_MODE"
    - "LIVINGAPARTMENTS_MODE"
    - "LIVINGAREA_MODE"
    - "NONLIVINGAPARTMENTS_MODE"
    - "NONLIVINGAREA_MODE"
    - "APARTMENTS_MEDI"
    - "BASEMENTAREA_MEDI"
    - "YEARS_BEGINEXPLUATATION_MEDI"
    - "YEARS_BUILD_MEDI"
    - "COMMONAREA_MEDI"
    - "ELEVATORS_MEDI"
    - "ENTRANCES_MEDI"
    - "FLOORSMAX_MEDI"
    - "FLOORSMIN_MEDI"
    - "LANDAREA_MEDI"
    - "LIVINGAPARTMENTS_MEDI"
    - "LIVINGAREA_MEDI"
    - "NONLIVINGAPARTMENTS_MEDI"
    - "NONLIVINGAREA_MEDI"
    - "TOTALAREA_MODE"
    - "OBS_30_CNT_SOCIAL_CIRCLE"
    - "DEF_30_CNT_SOCIAL_CIRCLE"
    - "OBS_60_CNT_SOCIAL_CIRCLE"
    - "DEF_60_CNT_SOCIAL_CIRCLE"
    - "DAYS_LAST_PHONE_CHANGE"
    - "FLAG_DOCUMENT_2"
    - "FLAG_DOCUMENT_3"
    - "FLAG_DOCUMENT_4"
    - "FLAG_DOCUMENT_5"
    - "FLAG_DOCUMENT_6"
    - "FLAG_DOCUMENT_7"
    - "FLAG_DOCUMENT_8"
    - "FLAG_DOCUMENT_9"
    - "FLAG_DOCUMENT_10"
    - "FLAG_DOCUMENT_11"
    - "FLAG_DOCUMENT_12"
    - "FLAG_DOCUMENT_13"
    - "FLAG_DOCUMENT_14"
    - "FLAG_DOCUMENT_15"
    - "FLAG_DOCUMENT_16"
    - "FLAG_DOCUMENT_17"
    - "FLAG_DOCUMENT_18"
    - "FLAG_DOCUMENT_19"
    - "FLAG_DOCUMENT_20"
    - "FLAG_DOCUMENT_21"

split_data:
  target: TARGET
  test_size: 0.4
  random_seed: 42

Logistic_regression:
  params:
    classification__penalty:
      - l2
      - l1
  cv: 5
  random_seed: 42
  scoring: roc_auc


score_model:
  target: TARGET
  metrics:
    - prob
    - bin

evaluate_performance:
  target: TARGET
  metrics:
    - roc_auc_score
    - confusion_matrix
    - accuracy_score
    - classification_report
    - precision_score
